### ISSUE TITLE
Improve background model 

### ISSUE THREAD

**Issue by darinakalins** [dkalina-vm21/carcounter#8]
Implement bg subtracktion using running average.
Th algorithm is:

1. Count 2 running averages with α = (0.01)^1/4 и α = (0.01)^1/8. (see https://docs.opencv.org/2.4/modules/core/doc/operations_on_arrays.html)
2.  Find their abs diff.
3. Binarize it (by otsu or manually chosen threshold.

**Comment by raddist** [comment]
Resolved by fbf412e2e99000aef2166b3ac441304bcede2249
